SPEED_SPRINTER = 1
SPEED_FAST_SHAMBLER = 2
SPEED_SHAMBLER = 3

CHARGER_NUM = 1
BOOMER_NUM = 2
RECLAIMER_NUM = 3
SPECIAL_TOTAL = 3
REAL_SPECIAL_NAME =
{
	"Charger",
	"Boomer",
	"Reclaimer"
}

CHARGER_CHANCE = 10
CHARGER_OUTFIT_NAME = "ChargerOutfit"
CHARGER_MIN_HP = 500.0
CHARGER_MAX_HP = 1000.0
CHARGER_CD = 250
CHARGER_ABILITY_RANGE = 1
CHARGER_MAX_RANGE_CHECK = 70
CHARGER_SPEED = SPEED_SPRINTER

BOOMER_CHANCE = 10
BOOMER_OUTFIT_NAME = "BoomerOutfit"
BOOMER_MIN_HP = 1000.0
BOOMER_MAX_HP = 1000.0
BOOMER_CD = 500
BOOMER_ABILITY_RANGE = 2
BOOMER_MAX_RANGE_CHECK = 70
BOOMER_SPEED = SPEED_SHAMBLER

RECLAIMER_CHANGE = 10
RECLAIMER_OUTFIT_NAME = "ReclaimerOutfit"
RECLAIMER_MIN_HP = 500.0
RECLAIMER_MIN_HP = 1000.0
RECLAIMER_CD = 250
RECLAIMER_ABILITY_RANGE = 5
RECLAIMER_MAX_RANGE_CHECK = 100
RECLAIMER_SPEED = SPEED_SPRINTER